---
repos:
  - repo: https://github.com/psf/black
    rev: 24.2.0
    hooks:
      - id: black
        args: [--target-version=py36]
  - repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        args: [
          # default black line length is 88
          --max-line-length=88,
          # Conflicts with black: E203 whitespace before ':'
          --extend-ignore=E203,
        ]
