---
name: Docker
on:
  push:
  pull_request:

jobs:
  test:
    name: Build docker image
    strategy:
      fail-fast: false
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Build docker image
        run: docker build .
